# Generated by Django 5.2.8 on 2025-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0003_alter_userprofile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
