# Generated by Django 5.2.8 on 2025-11-22 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0005_candidate_is_independent_candidate_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constituency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AP", "Andhra Pradesh"),
                            ("AR", "Arunachal Pradesh"),
                            ("AS", "Assam"),
                            ("BR", "Bihar"),
                            ("CT", "Chhattisgarh"),
                            ("GA", "Goa"),
                            ("GJ", "Gujarat"),
                            ("HR", "Haryana"),
                            ("HP", "Himachal Pradesh"),
                            ("JH", "Jharkhand"),
                            ("KA", "Karnataka"),
                            ("KL", "Kerala"),
                            ("MP", "Madhya Pradesh"),
                            ("MH", "Maharashtra"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="candidate_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="candidate_photos/"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="position",
            field=models.CharField(default="Candidate", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="voter_photos/"),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="candidates",
                to="votingApp.party",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="constituency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="votingApp.constituency",
            ),
        ),
    ]
