# Generated by Django 5.2.8 on 2025-11-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "votingApp",
            "0006_constituency_candidate_bio_candidate_candidate_photo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="constituency",
        ),
        migrations.DeleteModel(
            name="Constituency",
        ),
    ]
