# Generated by Django 5.2.8 on 2025-11-23 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0008_party_abbreviation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_photo",
        ),
    ]
