# Generated by Django 5.2.8 on 2025-11-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("votingApp", "0009_remove_userprofile_profile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="candidate_photo",
        ),
    ]
